2025-02-21T06:55:13.362Z - ERROR: An unexpected error occurred {"statusCode":500,"stack":"SyntaxError: Unexpected token ' ', ...\"password\": \"123\"\r\n}\r\"... is not valid JSON\n    at JSON.parse (<anonymous>)\n    at parse (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\node_modules\\body-parser\\lib\\types\\json.js:92:19)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\node_modules\\body-parser\\lib\\read.js:128:18\n    at AsyncResource.runInAsyncScope (node:async_hooks:211:14)\n    at invokeCallback (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\node_modules\\raw-body\\index.js:238:16)\n    at done (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\node_modules\\raw-body\\index.js:227:7)\n    at IncomingMessage.onEnd (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\node_modules\\raw-body\\index.js:287:7)\n    at IncomingMessage.emit (node:events:524:28)\n    at IncomingMessage.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1698:12)","method":"POST","url":"/api/v1/employees"}
2025-02-22T16:42:40.862Z - ERROR: An unexpected error occurred {"statusCode":500,"method":"GET","url":"/api/v1/employees/:1740237066143"}
2025-02-22T16:51:33.064Z - ERROR: An unexpected error occurred {"statusCode":500,"method":"GET","url":"/api/v1/employees/1234"}
2025-02-22T16:52:13.655Z - ERROR: An unexpected error occurred {"statusCode":500,"method":"GET","url":"/api/v1/employees/1234567"}
2025-02-22T16:52:15.317Z - ERROR: An unexpected error occurred {"statusCode":500,"method":"GET","url":"/api/v1/employees/1234567"}
2025-02-22T16:52:32.537Z - ERROR: An unexpected error occurred {"statusCode":500,"method":"GET","url":"/api/v1/employees/validEmployeeId123"}
2025-02-22T16:54:03.524Z - ERROR: An unexpected error occurred {"statusCode":500,"method":"GET","url":"/api/v1/employees/1739468407652"}
2025-02-22T16:56:37.441Z - ERROR: An unexpected error occurred {"statusCode":500,"method":"GET","url":"/api/v1/employees/:id"}
2025-02-22T16:57:04.373Z - ERROR: An unexpected error occurred {"statusCode":500,"method":"GET","url":"/api/v1/employees/:123456"}
2025-02-22T17:19:59.881Z - ERROR: An unexpected error occurred {"statusCode":500,"stack":"Error: Employee with ID :nonExistingEmployeeId1234 not found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:69:15\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:4:12)\n    at Object.updateEmployee (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:65:20)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:79:51\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:41:71\n    at new Promise (<anonymous>)","method":"PUT","url":"/api/v1/employees/:nonExistingEmployeeId1234"}
2025-02-22T17:20:47.630Z - ERROR: An unexpected error occurred {"statusCode":500,"stack":"Error: Employee with ID :id not found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:69:15\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:4:12)\n    at Object.updateEmployee (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:65:20)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:79:51\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:41:71\n    at new Promise (<anonymous>)","method":"PUT","url":"/api/v1/employees/:id"}
2025-02-22T17:20:49.450Z - ERROR: An unexpected error occurred {"statusCode":500,"stack":"Error: Employee with ID :id not found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:69:15\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:4:12)\n    at Object.updateEmployee (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:65:20)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:79:51\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:41:71\n    at new Promise (<anonymous>)","method":"PUT","url":"/api/v1/employees/:id"}
2025-02-23T06:09:16.453Z - ERROR: An unexpected error occurred {"statusCode":500,"method":"GET","url":"/api/v1/branches/invalidid1234"}
2025-02-23T06:09:33.875Z - ERROR: An unexpected error occurred {"statusCode":500,"method":"GET","url":"/api/v1/branches/:12345"}
2025-02-23T06:10:30.860Z - ERROR: An unexpected error occurred {"statusCode":500,"method":"GET","url":"/api/v1/branches/nonExistingBranch123"}
2025-02-23T06:17:03.255Z - ERROR: An unexpected error occurred {"statusCode":500,"stack":"Error: Branch with ID :id not found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\branchService.ts:62:15\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\branchService.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\branchService.ts:4:12)\n    at Object.updateBranch (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\branchService.ts:58:22)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:83:59\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:41:71\n    at new Promise (<anonymous>)","method":"PUT","url":"/api/v1/branches/:id"}
2025-02-23T06:17:41.394Z - ERROR: An unexpected error occurred {"statusCode":500,"stack":"Error: Branch with ID :id not found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\branchService.ts:62:15\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\branchService.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\branchService.ts:4:12)\n    at Object.updateBranch (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\branchService.ts:58:22)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:83:59\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:41:71\n    at new Promise (<anonymous>)","method":"PUT","url":"/api/v1/branches/:id"}
2025-02-23T06:18:57.552Z - ERROR: An unexpected error occurred {"statusCode":500,"stack":"Error: Branch with ID 1234567890 not found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\branchService.ts:62:15\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\branchService.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\branchService.ts:4:12)\n    at Object.updateBranch (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\branchService.ts:58:22)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:83:59\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:41:71\n    at new Promise (<anonymous>)","method":"PUT","url":"/api/v1/branches/1234567890"}
2025-02-23T06:18:59.976Z - ERROR: An unexpected error occurred {"statusCode":500,"stack":"Error: Branch with ID 1234567890 not found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\branchService.ts:62:15\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\branchService.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\branchService.ts:4:12)\n    at Object.updateBranch (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\branchService.ts:58:22)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:83:59\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:41:71\n    at new Promise (<anonymous>)","method":"PUT","url":"/api/v1/branches/1234567890"}
2025-02-23T06:22:21.167Z - ERROR: An unexpected error occurred {"statusCode":500,"stack":"Error: Branch with ID :id not found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\branchService.ts:81:15\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\branchService.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\branchService.ts:4:12)\n    at Object.deleteBranch (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\branchService.ts:77:65)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:107:29\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:41:71\n    at new Promise (<anonymous>)","method":"DELETE","url":"/api/v1/branches/:id?=1740290578066"}
2025-02-23T07:12:42.506Z - ERROR: An unexpected error occurred {"statusCode":500,"method":"GET","url":"/api/v1/employees/1740237066143"}
2025-02-23T07:12:55.163Z - ERROR: An unexpected error occurred {"statusCode":500,"method":"GET","url":"/api/v1/employees/1740237066143"}
2025-02-23T07:13:22.981Z - ERROR: An unexpected error occurred {"statusCode":500,"method":"GET","url":"/api/v1/employees/1740237066143"}
2025-02-23T07:13:39.142Z - ERROR: An unexpected error occurred {"statusCode":500,"method":"GET","url":"/api/v1/branches/1740290696642"}
2025-02-23T07:16:32.243Z - ERROR: An unexpected error occurred {"statusCode":500,"method":"GET","url":"/api/v1/employees/12345678"}
2025-02-23T07:28:53.734Z - ERROR: Employee not Found {"statusCode":404,"stack":"Error: Employee not Found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:57:25\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:38:58)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","method":"GET","url":"/api/v1/employees/12345678"}
2025-02-23T07:29:41.069Z - ERROR: An unexpected error occurred {"statusCode":500,"stack":"Error: Employee with ID 123456 not found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:69:15\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:4:12)\n    at Object.updateEmployee (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:65:20)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:81:51\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:41:71\n    at new Promise (<anonymous>)","method":"PUT","url":"/api/v1/employees/123456"}
2025-02-23T07:34:26.599Z - ERROR: An unexpected error occurred {"statusCode":500,"stack":"Error: Employee with ID 123456 not found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:69:15\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:4:12)\n    at Object.updateEmployee (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:65:20)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:81:51\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:41:71\n    at new Promise (<anonymous>)","method":"PUT","url":"/api/v1/employees/123456"}
2025-02-23T07:37:55.885Z - ERROR: An unexpected error occurred {"statusCode":500,"stack":"Error: Employee with ID 123456 not found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:69:15\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:4:12)\n    at Object.updateEmployee (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:65:20)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:81:51\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:41:71\n    at new Promise (<anonymous>)","method":"PUT","url":"/api/v1/employees/123456"}
2025-02-23T07:38:00.566Z - ERROR: An unexpected error occurred {"statusCode":500,"stack":"Error: Employee with ID 123456 not found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:69:15\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:4:12)\n    at Object.updateEmployee (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:65:20)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:81:51\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:41:71\n    at new Promise (<anonymous>)","method":"PUT","url":"/api/v1/employees/123456"}
2025-02-23T07:38:31.389Z - ERROR: Employee not Found {"statusCode":404,"stack":"Error: Employee not Found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:84:25\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:38:58)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","method":"PUT","url":"/api/v1/employees/123456"}
2025-02-23T07:39:37.517Z - ERROR: An unexpected error occurred {"statusCode":500,"stack":"Error: Employee with ID 1740237066143 not found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:88:15\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:4:12)\n    at Object.deleteEmployee (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:84:67)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:110:27\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:41:71\n    at new Promise (<anonymous>)","method":"DELETE","url":"/api/v1/employees/1740237066143"}
2025-02-23T07:40:22.036Z - ERROR: An unexpected error occurred {"statusCode":500,"stack":"Error: Employee with ID 1740296386312 not found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:88:15\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:4:12)\n    at Object.deleteEmployee (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:84:67)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:110:27\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:41:71\n    at new Promise (<anonymous>)","method":"DELETE","url":"/api/v1/employees/1740296386312"}
2025-02-23T07:41:30.636Z - ERROR: An unexpected error occurred {"statusCode":500,"stack":"Error: Employee with ID 1740296386312 not found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:88:15\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:4:12)\n    at Object.deleteEmployee (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\services\\userService.ts:84:67)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:110:27\n    at Generator.next (<anonymous>)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:41:71\n    at new Promise (<anonymous>)","method":"DELETE","url":"/api/v1/employees/1740296386312"}
2025-02-23T07:42:01.741Z - ERROR: Employee not Found {"statusCode":404,"stack":"Error: Employee not Found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:112:25\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\userController.ts:38:58)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","method":"DELETE","url":"/api/v1/employees/1740296386312"}
2025-02-23T07:49:13.209Z - ERROR: Branch not Found {"statusCode":404,"stack":"Error: Branch not Found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:60:25\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:38:58)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","method":"GET","url":"/api/v1/branches/1740290696642"}
2025-02-23T07:54:42.358Z - ERROR: Branch not Found {"statusCode":404,"stack":"Error: Branch not Found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:87:25\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:38:58)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","method":"PUT","url":"/api/v1/branches/1740290696642"}
2025-02-23T07:54:48.810Z - ERROR: Branch not Found {"statusCode":404,"stack":"Error: Branch not Found\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:116:25\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:38:58)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","method":"DELETE","url":"/api/v1/branches/1740290578066?="}
2025-02-23T08:05:54.518Z - ERROR: An unexpected error occurred {"statusCode":500,"stack":"SyntaxError: Expected double-quoted property name in JSON at position 149 (line 8 column 1)\n    at JSON.parse (<anonymous>)\n    at parse (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\node_modules\\body-parser\\lib\\types\\json.js:92:19)\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\node_modules\\body-parser\\lib\\read.js:128:18\n    at AsyncResource.runInAsyncScope (node:async_hooks:211:14)\n    at invokeCallback (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\node_modules\\raw-body\\index.js:238:16)\n    at done (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\node_modules\\raw-body\\index.js:227:7)\n    at IncomingMessage.onEnd (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\node_modules\\raw-body\\index.js:287:7)\n    at IncomingMessage.emit (node:events:524:28)\n    at IncomingMessage.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1698:12)","method":"POST","url":"/api/v1/employees"}
2025-02-23T08:10:24.737Z - ERROR: Name, adress, and phone are required {"statusCode":400,"stack":"Error: Name, adress, and phone are required\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:21:21\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:38:58)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","method":"POST","url":"/api/v1/branches"}
2025-02-23T08:12:13.887Z - ERROR: Name, adress, and phone are required {"statusCode":400,"stack":"Error: Name, adress, and phone are required\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:21:21\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:38:58)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","method":"POST","url":"/api/v1/branches"}
2025-02-23T08:12:42.362Z - ERROR: Name, adress, and phone are required {"statusCode":400,"stack":"Error: Name, adress, and phone are required\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:21:21\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:38:58)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","method":"POST","url":"/api/v1/branches"}
2025-02-23T08:13:15.940Z - ERROR: Name, adress, and phone are required {"statusCode":400,"stack":"Error: Name, adress, and phone are required\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:21:21\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:38:58)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","method":"POST","url":"/api/v1/branches"}
2025-02-23T08:13:20.286Z - ERROR: Name, adress, and phone are required {"statusCode":400,"stack":"Error: Name, adress, and phone are required\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:21:21\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:38:58)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","method":"POST","url":"/api/v1/branches"}
2025-02-23T08:14:28.946Z - ERROR: Name, adress, and phone are required {"statusCode":400,"stack":"Error: Name, adress, and phone are required\n    at C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:21:21\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\mowmi\\OneDrive\\Desktop\\Back-End-Assignment-2\\src\\api\\v1\\controllers\\branchController.ts:38:58)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","method":"POST","url":"/api/v1/branches"}
